#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rotationMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     extentionMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftDrive,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    verticalArm,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"
#include "F:\FTC Block Party\GlobVars.h"
#include "F:\FTC Block Party\GlobFuncs.c"







void HandleGameController1()
{
	GlobVars.threshold_ = 10;
	//GlobVars.max_power_ = 10.0;

	// left analog joystick
	// 127 to -128
	if( abs( joystick.joy1_x1 ) > GlobVars.threshold_ )
  {
  	// Add left joystick x-axis control code here
  }
  else
  {
  }
	if( abs( joystick.joy1_y1 ) > GlobVars.threshold_ )
  {
  	// Add left joystick y-axis control code here
  	motor[ LeftDrive ] = ApplyPower( joystick.joy1_y1, GlobVars.max_power_ );
  }
  else
  {
  	motor[ LeftDrive ] = 0;
  }

  // right analog joystick
	if( abs( joystick.joy1_x2 ) > GlobVars.threshold_ )
  {
  	// Add right joystick x-axis control code here
  }
  else
  {
  }
  if( abs( joystick.joy1_y2 ) > GlobVars.threshold_ )
  {
  	// Add right joystick y-axis control code here
	  motor[ RightDrive ] = ApplyPower( joystick.joy1_y2, GlobVars.max_power_ );
  }
  else
  {
  	motor[ RightDrive ] = 0;
  }

}


void HandleGameController2()
{
	GlobVars.threshold_ = 10;
	GlobVars.max_power_ = 100.0;

	// left analog joystick
	// 127 to -128
	if(  joystick.joy2_x1  > GlobVars.threshold_ )
  {
  	motor[rotationMotor] = 100;
  }
  else if( joystick.joy2_x1 < GlobVars.threshold_ )
  {
  	motor[rotationMotor] = -100;
  }
  else
  {
  	motor[rotationMotor] = 0;
  }
  if(  joystick.joy2_y1  > GlobVars.threshold_ )
  {
  	servo[verticalArm] = servo[verticalArm] + 5;
  	wait1Msec(10);
  }
  else
  {

  }

  // right analog joystick
	if( abs( joystick.joy2_x2 ) > GlobVars.threshold_ )
  {
  	// Add right joystick x-axis control code here
  }
  else
  {
  }
  if(  joystick.joy2_y2  > GlobVars.threshold_ )
  {
  	motor[extentionMotor] = 20;
  }
  else if( joystick.joy2_y2 > GlobVars.threshold_ )
  {
  	motor[extentionMotor] = -20;
  }
  else
  {
  	motor[extentionMotor] = 0;
  }
}

bool InitializeRobot()
{
	// Add robot initialization code here
	motor[ LeftDrive ] = 0;
	bMotorFlippedMode[ LeftDrive ] = false;
	motor[ RightDrive ] = 0;
	bMotorFlippedMode[ RightDrive ] = true;

	// Initialize global variables
	GlobVars.direction_ = 0;
	GlobVars.max_power_ = 100;

	return true;
}


// Main program that runs when executed
task main()
{

	// Initialize the robot
	if( !InitializeRobot() )
  {
  	// if init fails, fix robot here
	}


  ///////////////////////////////////////////////////////////////////////////
	// TEL-OP PHASE
  //
  // Place your robot specific tel-op phase code within this while loop
  //
  ///////////////////////////////////////////////////////////////////////////
  while( true )
  {
		getJoystickSettings( joystick );

		HandleGameController1();	// Drive the robot function
  	HandleGameController2();	// Pick up and drop game piece function


  }
}
