#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rotationMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     extentionMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftDrive,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    verticalArm,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"
#include "F:\FTC Block Party\GlobVars.h"
#include "F:\FTC Block Party\GlobFuncs.c"








void HandleGameController1()
{
	GlobVars.threshold_ = 10;



	if( abs( joystick.joy1_y1 ) > GlobVars.threshold_ )
  {
  	motor[ LeftDrive ] = ApplyPower( joystick.joy1_y1, GlobVars.max_power_ );
  }
  else
  {
  	motor[ LeftDrive ] = 0;
  }
  if( abs( joystick.joy1_y2 ) > GlobVars.threshold_ )
  {
	  motor[ RightDrive ] = ApplyPower( joystick.joy1_y2, GlobVars.max_power_ );
  }
  else
  {
  	motor[ RightDrive ] = 0;
  }
}




void HandleGameController2()
{
	GlobVars.threshold_ = 10;


	if( joystick.joy2_Buttons == 32 )
	{
			motor[extentionMotor] = 40;
	}
	else if( joystick.joy2_Buttons == 16 )
	{
		motor[extentionMotor] = -40;
	}
	else
	{
			motor[extentionMotor] = 0;
	}

/*
	for( int button = 0; button < 12; button++ )
  {
  	if( ( joystick.joy2_Buttons >> button ) & 0x01 )
  	{
  		switch( button )
  		{
  			case 0:	// button 1 pressed
  				break;
  			case 1:	// button 2 pressed
  				break;
  			case 2:	// button 3 pressed
  				break;
  			case 3:	// button 4 pressed
  				break;
  			case 4:	// button 5 pressed
  				motor[extentionMotor] = 40;
//  				wait1Msec(10);
  				break;
  			case 5:	// button 6 nd
					motor[extentionMotor] = -40;
//  				wait1Msec(10);
  				break;
  			case 6:	// button 7 pressed
  				break;
  			case 7:	// button 8 pressed
  				break;
  			case 8:	// button 9 pressed
  				break;
  			case 9:	// button 10 pressed
  				break;
  			case 10:	// button 11 pressed
  				break;
  			case 11:	// button 12 pressed
  				break;
  			default:
  				break;
  			}
  		}
  		else
  		{
  			motor[extentionMotor] = 0;
  		}
  	}
*/



if(  abs(joystick.joy2_x1)  > GlobVars.threshold_ )
  {
  	motor[rotationMotor] = ApplyPower( joystick.joy2_x1, GlobVars.max_power_ );
  }
else
  {
  	motor[rotationMotor] = 0;
  }
	if( abs( joystick.joy2_y1 ) > GlobVars.threshold_ )
  {

  }
  else
  {

  }

	if( abs( joystick.joy2_x2 ) > GlobVars.threshold_ )
  {

  	if( joystick.joy2_x2 > 0 )
  	{
  		if( ServoValue[verticalArm] < 245 )
  		{
 		 servo[verticalArm] += 5;
// 		 wait1Msec(1);
 			}
		}
		if( joystick.joy2_x2 < 0 )
		{
			if( ServoValue[verticalArm] > 10 )
			{
		servo[verticalArm] -= 5;
// 		wait1Msec(1);
 			}
 		}
  }
  else
  {
  }
  if( abs( joystick.joy2_y2 ) > GlobVars.threshold_ )
  {

  }
  else
  {

  }

}

bool InitializeRobot()
{

  motor[ motorA ] = 0;
	motor[ LeftDrive ] = 0;
	bMotorFlippedMode[ LeftDrive ] = false;
	motor[ RightDrive ] = 0;
	bMotorFlippedMode[ RightDrive ] = true;


	GlobVars.direction_ = 0;
	GlobVars.max_power_ = 100;

	return true;
}

task main()
{

	if( !InitializeRobot() )
  {
	}

  while( true )
  {
		getJoystickSettings( joystick );

		HandleGameController1();
		HandleGameController2();

 		 wait1Msec(10);

  }
}
