#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          RightDrive,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftDrive,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");

#include "JoystickDriver.c"
//#include "hitechnic-irseeker-v2r.h"

const int threshold = 10;

// Transfer function to convert joystick position to power level
short ApplyPower( short joystick_position, float max_power )
{
	float power;

	if( joystick_position < 0)
	{
		power = ( (float)joystick_position / 128.0 ) * max_power;
		return( (short)power );
	}
	else
	{
		power = ( (float)joystick_position / 127.0 ) * max_power;
		return( (short)power );
	}
}

// Code to manage the primary game controller
void HandleJoystick1()
{
  // left analog joystick
	// 127 to -128
	if( abs( joystick.joy1_x1 ) > threshold )
  {
  	// Add left joystick x-axis control code here
  	float max_power = 50;
  	motor[ motorA ] = ApplyPower( joystick.joy1_x1, max_power );
  }
  else
  {
  	motor[ motorA ] = 0;
  }
  if( abs( joystick.joy1_y1 ) > threshold )
  {
  	// Add left joystick y-axis control code here
  }
  else
  {
  }

  // right analog joystick
	if( abs( joystick.joy1_x2 ) > threshold )
  {
  	// Add right joystick x-axis control code here
  }
  else
  {
  }
  if( abs( joystick.joy1_y2 ) > threshold )
  {
  	// Add right joystick y-axis control code here
  }
  else
  {
  }

  // buttons
  // 12-bit bitmap with a bit for each button
  for( int button = 0; button < 12; button++ )
  {
  	if( ( joystick.joy1_Buttons >> button ) & 0x01 )
  	{
  		switch( button )
  		{
  			case 0:	// button 1 pressed
  				break;
  			case 1:	// button 2 pressed
  				break;
  			case 2:	// button 3 pressed
  				break;
  			case 3:	// button 4 pressed
  				break;
  			case 4:	// button 5 pressed
  				break;
  			case 5:	// button 6 pressed
  				break;
  			case 6:	// button 7 pressed
  				break;
  			case 7:	// button 8 pressed
  				break;
  			case 8:	// button 9 pressed
  				break;
  			case 9:	// button 10 pressed
  				break;
  			case 10:	// button 11 pressed
  				break;
  			case 11:	// button 12 pressed
  				break;
  			default:
  				break;
  			}
  		}
  	}

  // tophat buttons
  // -1 if not pressed
  // 0 - 7 for the eight positions
	switch( joystick.joy1_TopHat )
	{
		case 0:	// top button
			break;
		case 1:	// upper right button
			break;
		case 2:	// right button
			break;
		case 3:	// lower right button
			break;
		case 4:	// bottom button
			break;
		case 5:	// lower left button
			break;
		case 6:	// left button
			break;
		case 7:	// upper left button
			break;
		default:
			break;
	}
}

// Code to manage the secondary game controller
void HandleJoystick2()
{
  // left analog joystick
	// 127 to -128
	if( abs( joystick.joy2_x1 ) > threshold )
  {
  	// Add left joystick x-axis control code here
	  motor[ motorB ] = ApplyPower( joystick.joy1_y1, 50.0 );
  }
  else
  {
  	motor[ motorB ] = 0;
  }
  if( abs( joystick.joy2_y1 ) > threshold )
  {
  	// Add left joystick y-axis control code here
  }
  else
  {
  }

  // right analog joystick
	if( abs( joystick.joy2_x2 ) > threshold )
  {
  	// Add right joystick x-axis control code here
  }
  else
  {
  }
  if( abs( joystick.joy2_y2 ) > threshold )
  {
  	// Add right joystick y-axis control code here
  }
  else
  {
  }

  // buttons
  // 12-bit bitmap with a bit for each button
  for( int button = 0; button < 12; button++ )
  {
  	if( ( joystick.joy2_Buttons >> button ) & 0x01 )
  	{
  		switch( button )
  		{
  			case 0:	// button 1 pressed
  				break;
  			case 1:	// button 2 pressed
  				break;
  			case 2:	// button 3 pressed
  				break;
  			case 3:	// button 4 pressed
  				break;
  			case 4:	// button 5 pressed
  				break;
  			case 5:	// button 6 pressed
  				break;
  			case 6:	// button 7 pressed
  				break;
  			case 7:	// button 8 pressed
  				break;
  			case 8:	// button 9 pressed
  				break;
  			case 9:	// button 10 pressed
  				break;
  			case 10:	// button 11 pressed
  				break;
  			case 11:	// button 12 pressed
  				break;
  			default:
  				break;
  			}
  		}
  	}

  // tophat buttons
  // -1 if not pressed
  // 0 - 7 for the eight positions
	switch( joystick.joy2_TopHat )
	{
		case 0:	// top button
			break;
		case 1:	// upper right button
			break;
		case 2:	// right button
			break;
		case 3:	// lower right button
			break;
		case 4:	// bottom button
			break;
		case 5:	// lower left button
			break;
		case 6:	// left button
			break;
		case 7:	// upper left button
			break;
		default:
			break;
	}
}

bool InitializeRobot()
{
	// Add robot initialization code here
	return true;
}

bool KillRobot()
{
	// Add kill robot code here
	return false;
}

task main()
{
  if( !InitializeRobot() )
  {
  	// fix robot code here
	}

//  waitForStart();	// Wait for the beginning of autonomous phase

  // Place your robot specific autonomous code here

	while( true )
  {
		getJoystickSettings( joystick );

		HandleJoystick1();
  	HandleJoystick2();

  	if( KillRobot() )
  	{
  		break;
  	}
  }
}
