#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rotationMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     extentionMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftDrive,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    verticalArm,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

*/

#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"
#include "F:\FTC Block Party\GlobVars.h"
#include "F:\FTC Block Party\GlobFuncs.c"







bool InitializeRobot()
{

  motor[ motorA ] = 0;
	motor[ LeftDrive ] = 0;
	bMotorFlippedMode[ LeftDrive ] = false;
	motor[ RightDrive ] = 0;
	bMotorFlippedMode[ RightDrive ] = true;


	GlobVars.direction_ = 0;
	GlobVars.max_power_ = 100;

	return true;
}

task main()
{

}
